### ISSUE TITLE
Add support for k8s

### ISSUE THREAD

**Issue by jabez000** [yidongnan/grpc-spring-boot-starter#257]

**Comment by ST-DDT** [comment]
Kubernetes support is already implicitly available.

You can use the `DnsNameResolverProvider` that is provided by grpc-java
and enable service based resolving using:
`-Dio.grpc.internal.DnsNameResolverProvider.enable_grpclb=true`

Then configure the client's target address as: 
`dns:///myservice.mynamespace` (you might have to append `.svc.cluster.local` or something similar.)

Finally define your kubernetes service as:

````yaml
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: mynamespace
spec:
  ports:
  - name: grpclb # The name is important
    port: 9090
    protocol: TCP
    targetPort: grpc
````

Does this help you or is there anything else you need?

**Comment by jabez000** [comment]
thinks !

**Comment by kensixx** [comment]
I've tried this, but I'm getting connection timeout to the gRPC server. 
I've exposed the gRPC server on port `9797`.

And this is the current K8s Service of my gRPC Server Spring Boot app:
```
kind: Service
apiVersion: v1
metadata:
  name: grpc-wc-service
  namespace: default
  labels:
    app: grpc-wc-service
spec:
  ports:
  - name: grpclb # The name is important
    port: 9797
    protocol: TCP
    targetPort: grpc
  selector:
    app: grpc-wc-service
  type: ClusterIP
```

I'm reaching the gRPC server in my gRPC client using this setting:
```
grpc:
  client:
    grpc-wc-service:
      address: 'dns:///grpc-wc-service.default.cluster.local'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
```

I'm getting a connection timeout from the server. Can you point where am I going wrong? I've been stuck for days..

**Comment by ST-DDT** [comment]
If you use a non standard port you have to specify it in the address.

Older versions of grpc < 1.25 (?) used the environment variable to turn service entry resolution on, but this requires the service port to be named `grpclb`. Newer versions of grpc require the grpc-lb library to turn this feature on, but still require the specific port name.

As an alternative you could add spring-cloud-kubernetes and use its `DiscoveryClient` to resolve the address (Not tested).
`discovery:///service-name`

**Comment by ST-DDT** [comment]
The easiest solution is probably changing the port in the service definition to 80.

TODO: Update documentation accordingly

**Comment by kensixx** [comment]
Thank you so much for the response! =)
So, I'll change service definition port like so? Please see example:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: grpc-wc-service
  namespace: default
  labels:
    app: grpc-wc-service
spec:
  ports:
  - name: grpclb # The name is important
    port:  ̶9̶7̶9̶7̶ -> 80
    protocol: TCP
    targetPort: grpc
  selector:
    app: grpc-wc-service
  type: ClusterIP
```

Should this reach my gRPC Server Spring Boot app exposed in gRPC port 9797?

**Comment by ST-DDT** [comment]
The service yaml looks good to me.

The ports only have to be unique inside a single service. I use port 80 or 443 for most of my services in kubernetes.

If you use nodePorts then those must be unique across the entire cluster.

**Comment by kensixx** [comment]
Okay, wait. Thank you for your advice! I'll try this one out. I'll give you feedback if I manage to work this one out =)

**Comment by kensixx** [comment]
Hi, I resolved it on my end! Thank you so much for your help!

Posting here my current Pod definitions for other to see:
**gRPC Server - Spring Boot app -** `application.yml`:
```yaml
server:
  port: 0 <-- will find any available port for Spring Boot to run
grpc:
  server:
    port: ${GRPC_PORT} <-- we let Pod env decide what gRPC port to use
```

**gRPC Client - Spring Boot app -** `application.yml`:
```yaml
grpc:
  client:
    grpc-wc-service:
      address: 'dns:///grpc-wc-service.default.cluster.local'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
```

1. in the K8s Deployment definition, you need to expose the port you assigned as the gRPC port like so:
```yaml
containers:
        # You may reach this pod via http://grpc-wc-service.cluster9.svc.cluster.local.
        # See cluster9/services/grpc-wc-service.yaml
        - name: grpc-wc-service
          image: "grpc-wc-service:dev"
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: uat
            # 1. what you assign here,
            - name: GRPC_PORT
              value: "9797"
          ports:
            # 2. you need to expose here as well. K8s Service should point to this port.
            # This is different from the server port that the Spring Boot app itself will run.
            # this must be the gRPC PORT ASSIGNED TO application.yml!
            - containerPort: 9797
              name: grpc-port
              protocol: TCP
```

2. for the K8s Service, targetPort must point to the exposed gRPC Port, in this case `9797` like so:
```yaml
services/grpc-wc-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: grpc-wc-service
  namespace: default
  labels:
    app: grpc-wc-service
spec:
  ports:
  - name: grpclb # The name is important
    port: 80
    protocol: TCP
    # see deployments/grpc-wc-service > port 9797 name
    targetPort: grpc-port
  selector:
    app: grpc-wc-service
  type: ClusterIP
```

Although, did the `grpc-lb` K8s Service name and the `-Dio.grpc.internal.DnsNameResolverProvider.enable_grpclb=true` flag had any use as well? Please confirm! I'll also test this later by removing them.
