### ISSUE TITLE
local-grpc-client配置错误

### ISSUE THREAD

**Issue by chenyu9390** [yidongnan/grpc-spring-boot-starter#305]
**The context**
examples配置错误
**The bug**
事例配置
````yaml
grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9898'
````
测试发现改变IP没有效果,实际应该是
````yaml
grpc:
  client:
    local-grpc-server:
      host: '127.0.0.1'
      port: 9898
````
maven依赖:
````xml
<dependency>
    <groupId>net.devh</groupId>
    <artifactId>grpc-client-spring-boot-starter</artifactId>
    <version>2.1.0.RELEASE</version>
    <type>pom</type>
</dependency>
````
