### ISSUE TITLE
The Class-Path manifest attribute for grpc-netty-shaded-1.27.1.jar referenced one or more files do not exist

### ISSUE THREAD

**Issue by alvindaiyan** [yidongnan/grpc-spring-boot-starter#345]
Hi, I got a problem here which not affect the springboot start, but I'm not sure why this is happening

Here is the log:

`
The Class-Path manifest attribute in /Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/grpc-netty-shaded-1.27.1.jar referenced one or more files that do not exist: file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/grpc-core-1.27.1.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/grpc-api-1.27.1.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/gson-2.8.6.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/annotations-4.1.1.4.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/error_prone_annotations-2.3.4.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/perfmark-api-0.19.0.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/grpc-context-1.27.1.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/jsr305-3.0.2.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/animal-sniffer-annotations-1.18.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/guava-28.1-android.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/failureaccess-1.0.1.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar,file:/Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/checker-compat-qual-2.5.5.jar,file:/Users/daiyan5/
`

**The application's environment**

Which versions do you use?
* Spring (boot): 2.1.6.RELEASE
* grpc-java:
* grpc-spring-boot-starter:2.7.0.RELEASE
* java: 8

What can I do to fix this?

**Comment by ST-DDT** [comment]
Where did you get this (warning?) message?
Could you paste that `Class-Path manifest attribute in /Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/grpc-netty-shaded-1.27.1.jar` here?

**Comment by alvindaiyan** [comment]
> Where did you get this (warning?) message?
> Could you paste that `Class-Path manifest attribute in /Users/daiyan5/.m2/repository/io/grpc/grpc-netty-shaded/1.27.1/grpc-netty-shaded-1.27.1.jar` here?

Here is a screenshot of my log. If I run from cmd line, it's fine but not IDE (intellij).


<img width="1562" alt="Screen Shot 2020-04-08 at 11 11 18 AM" src="https://user-images.githubusercontent.com/2063558/78740678-f9675280-7989-11ea-986e-9246c6ffe7c9.png">

**Comment by ST-DDT** [comment]
For future reference, this is the content of `grpc-netty-shaded`'s MAINFEST.MF file:

````yaml
Manifest-Version: 1.0
Implementation-Title: grpc-netty-shaded
Target-Compatibility: 1.7
Implementation-Version: 1.27.1
Built-By: root
Source-Compatibility: 1.7
Class-Path: grpc-core-1.27.1.jar grpc-api-1.27.1.jar gson-2.8.6.jar an
 notations-4.1.1.4.jar error_prone_annotations-2.3.4.jar perfmark-api-
 0.19.0.jar grpc-context-1.27.1.jar jsr305-3.0.2.jar animal-sniffer-an
 notations-1.18.jar guava-28.1-android.jar failureaccess-1.0.1.jar lis
 tenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar checker-c
 ompat-qual-2.5.5.jar j2objc-annotations-1.3.jar
Built-JDK: 1.8.0_131
````

Maybe since this is purely related to grpc-java's libraries, you should consider asking the question there instead. As an alternative, you could ask the intellij developers/community for advise.

As for this library, there is nothing we can do about that warning. If you open an issue upstream or find a solution otherwise, please link it here.
