### ISSUE TITLE
I want to dynamically change the server during operation without the need for a registry, what should I do?

### ISSUE THREAD

**Issue by jianghu-coding** [yidongnan/grpc-spring-boot-starter#519]
I want to dynamically change the server during operation without the need for a registry, what should I do?

```yaml
grpc:
  client:
    grpc-crm-worker-server:
      address: 'static://172.20.48.19:9999'
```
change config to
```yaml
grpc:
  client:
    grpc-crm-worker-server:
      address: 'static://172.20.48.19:9998'
```
