### ISSUE TITLE
Keepalive behavior functional?

### ISSUE THREAD

**Issue by uweschaefer** [yidongnan/grpc-spring-boot-starter#570]
**The context**

We occasionally encounter a problem with long running (days) streams. On the Server-Side there is an exception popping up about the channel not being ready for writes and therefore the channel is closed.
However, the client does not seem to notice.

**The question**

We configured Keepalive settings from which our expectation was, that such a situation should be detected on the protocol level.

Server:
```yaml
grpc:
  server:
    permit-keep-alive-without-calls: true
    permit-keep-alive-time: 20
    keep-alive-without-calls: true
    keep-alive-time: 30
    enableKeepAlive: true
```

Client:

```yaml
grpc:
  client:
    someChannel:
      max-inbound-message-size: 20971520
      enable-keep-alive: true
      keep-alive-without-calls: true
      keep-alive-time: 110

```

Why doesn't the consumer recognize the server being gone?

**Stacktraces and logs**

The ServerCallStreamObserver is neither canceled, nor ready (for quite some time - we wait up to 60secs for it to become ready).
Is this expected? 

**The application's environment**

Which versions do you use?
* Spring (boot): 2.5
* grpc-java: 1.30.2
* grpc-spring-boot-starter: 2.11.0
* java: version + architecture (64bit?) java8-64bit

**Additional information**

* Did it ever work before?

Happens occasionally

* How can we reproduce it?

we're struggeling ourselves. it LOOKS like happening only with very long-lasting communications via a load balancer on amazon. Not sure, if the LB has any influence though.
