### ISSUE TITLE
Configure discovery metadata in applicaiton.yml is not effective.

### ISSUE THREAD

**Issue by HAo99** [yidongnan/grpc-spring-boot-starter#612]
**The bug**

here's my applicaiton.yml

```yml
spring:
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: localhost:8848
        metadata:
          version: v1
```

I ran the server.  But only got these metadatas on the Nacos server.

```
gRPC_port=41000
preserved.register.source=SPRING_CLOUD
```

It didn't include the `version: v1` which I configured in application.yml. I tried Consul as well. It had the same problem.

But it is ok to configure like this (see below).

```java
@EnableDiscoveryClient
@SpringBootApplication
public class Application {

    @Autowired
    private NacosRegistration nacosRegistration;

    @PostConstruct
    public void init() {
        if (nacosRegistration != null) {
            nacosRegistration.getMetadata().put("version", "1");
            nacosRegistration.
        }
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```

**The application's environment**

Which versions do you use?
* Spring (boot): 2.5.6
* grpc-java: 1.42.1
* grpc-spring-boot-starter: 2.13.0.RELEASE
* java: 11.0.11(64bit)
