### ISSUE TITLE
 Expose properties for Metric tag names

### ISSUE THREAD

**Issue by pluttrell** [yidongnan/grpc-spring-boot-starter#702]
Please consider adding properties that users can easily customize for the metric tag names: `service`, `method`, `method.type`, `status.code`.

**Comment by ST-DDT** [comment]
Please also report/request that feature there as we will eventually switch to that one.
https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc

**Comment by pluttrell** [comment]
A [Micrometer PR](https://github.com/micrometer-metrics/micrometer/issues/3222) has been added to enable customization of the classes in Micrometer itself.

For this PR (in this starter repo), please add configurable Spring Boot properties to configure these. I wonder if something like the following might make sense:
```yaml
grpc:
  server:
    metrics:
      processing-duration:
        meter-id: grpc.server.processing.duration
        tags:
          service-name: service
          method-name: rpc
          method-type: rpc.type
          status-code: status.code
```
