### ISSUE TITLE
eureka discovery

### ISSUE THREAD

**Issue by n0mer** [yidongnan/grpc-spring-boot-starter#71]
Hello @yidongnan , can you please confirm that cloud-discovery via Eureka is working?

I mean if i:
* annotate my service with `@GrpcClient("rpc-service")`, and configure eureka-client
* `spring.application.name` for rpc server is `rpc-service`, and it is registered properly on Eureka server

Then i do not need this part in application.yml:

```yaml
grpc:
  client:
    rpc-service:
      host:
        - rpc-service.domain.tld
      port:
        - 1234
```

Is that correct assumption? If not - how exactly this spring-cloud & eureka integration supposed to work, what for?

Thanks in advance.

Best regards,
Nik
