### ISSUE TITLE
grpc.client.port missing error when deploying to k8s

### ISSUE THREAD

**Issue by alozano3** [yidongnan/grpc-spring-boot-starter#731]
**The bug**

I am trying to test a simple grpc client on K8s. Everything works on local, but when I deploy on k8s I get the error below. Obviously, I don't have any property named  `grpc.client.port` so it is strange. It may be related to #584. I am using _static_ in the address using the pod IP directly instead of _dns_ for test purposes.

**Stacktrace and logs**
```
Description:

Failed to bind properties under 'grpc.client.port' to net.devh.boot.grpc.client.config.GrpcChannelProperties:

    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [net.devh.boot.grpc.client.config.GrpcChannelProperties]


Action:

Update your application's configuration
```

**The application's environment**

```
grpc:
  client:
    employee: 
      address: static://7.22.33.200:9090
      negotiation-type: plaintext  
```

Which versions do you use?
* Spring (boot): 2.6.7
* grpc-java:
* grpc-client-spring-boot-starter: 2.13.1
* java: 11

**Comment by ST-DDT** [comment]
The error message doesn't fit the configuration you have provided.

From the error message I assume that you have a config similar to this one:

````yaml
grpc:
  client:
    port: 9090
````

Did you maybe swap `grpc.server.port` with `grpc.client.port` by accident?
