### ISSUE TITLE
@GrpcClient is null spring boot 3

### ISSUE THREAD

**Issue by Moh3n75** [yidongnan/grpc-spring-boot-starter#884]
I am making grpc client using net.devh.grpc-client-spring-boot-starter

Client:

```
@Service
public class SystemService {
    @GrpcClient("handyman-client")
    StatusServiceGrpc.StatusServiceBlockingStub handymanClient;

    public VersionResponse getHandymanVersion() {
        return handymanClient.getVersion(Empty.newBuilder().build());
    }
}
```
application.yaml:

```
grpc:
  client:
    handyman-client:
      address: static://localhost:8080
      negotiationType: plaintext
```
In runtime handymanClient is null. Tried spring boot versions from 3.0.0 to 3.0.2. Lowering the spring boot version to 2.7.0 solves the problem - the client is being created now.

Is there a workaround to make it work on spring boot 3?
