### ISSUE TITLE
客户端和服务端在同一个项目中，出现的"this.stub is null"问题

### ISSUE THREAD

**Issue by hanweidong** [yidongnan/grpc-spring-boot-starter#886]
**The context**

What do you wish to achieve?

**The question**

你好，我尝试在一个项目中启动客户端和服务端，当我调用client的controller发送消息时，提示"this.stub" is null，麻烦问一下这是怎么回事哈

**The application's environment**

Which versions do you use?
* Spring (boot): 3.0.6
* grpc-java: 3.22.0
* grpc-spring-boot-starter: 2.14.0.RELEASE
* java: version + architecture (64bit?) 17
* Other relevant libraries...

**Additional information**

* How can we reproduce it?
我的application.yaml文件如下：
```
grpc:
  server:
    port: 9898
  client:
    local-grpc-server:
      address: static://127.0.0.1:9898
      negotiationType: plaintext
```
grpc client如下：
```
@Service
public class GrpcClientService {

  @GrpcClient("local-grpc-server")
  private RPCAlertServiceGrpc.RPCAlertServiceBlockingStub stub;

  public String sendMessage() {
    RPCAlertRequest request = RPCAlertRequest.newBuilder()
      .setEventType(EventType.DATA_COLLECT)
      .setEventLevel(EventLevel.HIGH)
      .build();
    RPCAlertResponse response = stub.sendEventStatus(request);
    return response.getMessage();
  }
}
```
