### ISSUE TITLE
How to autowire a GRPC stub

### ISSUE THREAD

**Issue by muraliweb9** [yidongnan/grpc-spring-boot-starter#897]
Unable to initialise context

Initialise the context

Unable to initialise the Context

What's the problem? What's not working? What's missing and why do you need it?

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of constructor in com.interview.carworkflowcloud.process.FinaliseBooking required a bean of type 'com.interview.proto.carrecords.service.RecordsServiceGrpc$RecordsServiceBlockingStub' that could not be found.


Action:

Consider defining a bean of type 'com.interview.proto.carrecords.service.RecordsServiceGrpc$RecordsServiceBlockingStub' in your configuration.


Process finished with exit code 1

```

**The application's environment**

Which versions do you use?
* Spring (boot): 3.0.6
* grpc-java: Bundled with 2.14.0.RELEASE
* grpc-spring-boot-starter: 3.0.6
* java: version + architecture (64bit?) 17 64 bit
* Other relevant libraries...

Bean configuration:
```
@Configuration
@GrpcClientBeans({
        @GrpcClientBean(
                clazz = RecordsServiceGrpc.RecordsServiceBlockingStub.class,
                beanName = "blockingStub",
                client = @GrpcClient("car-records-app"))
})
class GrpcStubConfig {
    @Bean
    public FinaliseBooking csBlockingStub(
            @Autowired ZeebeClientWrapper zeebeClient,
            @Autowired DiscoveryClient discoveryClient,
            @Autowired RecordsServiceGrpc.RecordsServiceBlockingStub stub) {
        return new FinaliseBooking(zeebeClient, discoveryClient, stub);
    }
}
```

spring factories workaround is added.

```
@Configuration
@ImportAutoConfiguration({
    net.devh.boot.grpc.client.autoconfigure.GrpcClientAutoConfiguration.class,
    net.devh.boot.grpc.client.autoconfigure.GrpcClientMetricAutoConfiguration.class,
    net.devh.boot.grpc.client.autoconfigure.GrpcClientHealthAutoConfiguration.class,
    net.devh.boot.grpc.client.autoconfigure.GrpcClientSecurityAutoConfiguration.class,
    net.devh.boot.grpc.client.autoconfigure.GrpcClientTraceAutoConfiguration.class,
    net.devh.boot.grpc.client.autoconfigure.GrpcDiscoveryClientAutoConfiguration.class,
    net.devh.boot.grpc.common.autoconfigure.GrpcCommonCodecAutoConfiguration.class,
    net.devh.boot.grpc.common.autoconfigure.GrpcCommonTraceAutoConfiguration.class
})
class GrpcConfig {}
```

application.yml

```
grpc:
  client:
    car-records-app:
      address: discovery:///car-records-app
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
      config:
        enabled: false


```
I have Consul running on localhost:8500 with a service named car-records-app registered to it.

From documentation https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html I am thinking maybe I am missing a trick with the stub factory.
